### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by brucou** [kaisermann/svelte-css-vars#2]
@kaisermann I simply put your demo in a svelte REPL: https://svelte.dev/repl/685251e3c38e443abb47ba8e99171568?version=3.18.2

Could be useful to add to the README?

**Comment by kaisermann** [comment]
Hey @brucou! Thanks for putting it in a REPL, but the readme already has a link to a repl 😆It's on the `Example` title. I'll probably change it to something more explicit! Thanks again :)
